install.packages("e1071")
library("e1071")
probplot(area,qdist=qlnorm,xlab="failure time",ylab="lognormal probability",line = F) 
plot(x=seq(1:616)/617,y=area,log='x',type='l')
setwd("/home2/zban/Followupp/scripts/weimeanscr/text/")
area=as.numeric(as.matrix(read.table("areasqkm")))
ta=as.numeric(as.matrix(read.table("basTa.daily.txt")))
pa=as.numeric(as.matrix(read.table("Pa.txt")))
area=sort(area)
areacdf=ecdf(area)
p=qnorm(seq(1:616)/617)
plot(pa,area,type="l")
areacdf_val=areacdf(area)
areacdf_val[616]=0.9999
areaz=qnorm(areacdf_val)
ta=sort(ta)
tacdf=ecdf(ta)
tacdf_val=tacdf(ta)
tacdf_val[616]=0.9999
taz=qnorm(tacdf_val)
pa=sort(pa)
pacdf=ecdf(pa)
pacdf_val=pacdf(pa)
pacdf_val[616]=0.9999
paz=qnorm(pacdf_val)
par(mfrow=c(3,1),tck=-0.02,mgp=c(2,0.5,0))
plot(x=areaz,y=area,type='s',xlab="Z-score for cumulative probability",ylab="Basin drainage area (sqkm)")
plot(x=taz,y=ta,type='s',xlab="Z-score for cumulative probability",ylab="Basin average annual mean \ntemperature (degree C)")
plot(x=paz,y=pa,type='s',xlab="Z-score for cumulative probability",ylab="Basin average annual precipitation (mm)")
plot(x=p,y=area,type='s',xlab="Z-score for cumulative probability",ylab="Basin drainage area (sqkm)")
plot(x=p,y=ta,type='s',xlab="Z-score for cumulative probability",ylab="Basin average annual mean \ntemperature (degree C)")
plot(x=p,y=pa,type='s',xlab="Z-score for cumulative probability",ylab="Basin average annual precipitation (mm)")
#plot(areacdf,xlab="Basin drainage area (sqkm)",ylab="Cumulative probability",main="",cex.lab=1.5,cex.main=1.5,cex.axis=1.5)
#plot(tacdf,xlab="Basin average annual mean temperature (degree C)",ylab="Cumulative probability",main="",cex.lab=1.5,cex.main=1.5,cex.axis=1.5)
#plot(pacdf,xlab="Basin average annual precipitation (mm)",ylab="Cumulative probability",main="",cex.lab=1.5,cex.main=1.5,cex.axis=1.5)
plot()